### ISSUE TITLE
(well a question) does this only change innerHTML of an element?

### ISSUE THREAD

**Issue by user670** [recurser/jquery-i18n#17]
as the title says.

If you wonder why would anyone modify anything other than innerHTML, think about `<input type="button" value="text to display"></input>`.

**Comment by recurser** [comment]
@user670 yes it currently only modifies `innerHTML` unfortunately. It uses jQuery's [.html()](http://api.jquery.com/html/#html-htmlString) method under the good [see implementation](https://github.com/recurser/jquery-i18n/blob/09a6053b7ebbfa80b3e393aa7a3e96b578e5e7b9/src/jquery.i18n.js#L99).

In the example above I'd recommend trying to use a `<button>text to display</button>` instead of an `<input />` if that is an option.
